name: "Agent HQ Guard"
description: "Validates Agent HQ manifests and enforces per-run guardrails."
author: "Personal R&D passion project"
inputs:
  policy:
    description: "Path to the Agent HQ Guard policy YAML"
    required: false
  manifest_glob:
    description: "Glob pattern to locate action credential manifests"
    required: true
  budget_tokens:
    description: "Override max tokens for run"
    required: false
    default: "0"
  github_token:
    description: "GitHub token for PR context (changes/approvals)"
    required: false
  changes:
    description: "Comma-separated list of changed files (overrides PR detection)"
    required: false
  changes_file:
    description: "Path to a newline-delimited changed files list"
    required: false
  approvals:
    description: "Approved review count (overrides PR detection)"
    required: false
outputs:
  allow:
    description: "True if run passes guardrails"
  reasons:
    description: "JSON array of reasons for denial"
  annotations:
    description: "JSON array of annotation objects (path/message)"
  result_path:
    description: "Path to the generated evaluation JSON"
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  color: "purple"
  icon: "shield"
