name: Protected Path Guard Example

on:
  pull_request:
    branches: [main]

jobs:
  guarded-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Produce manifest with protected changes
        run: |
          mkdir -p out
          cat > infra/terraform.tf <<'TF'
          resource "dummy" "example" {}
          TF
          cat > out/manifest.json <<'JSON'
          {
            "version": "0.1.0",
            "run_id": "protected-run",
            "repository": {
              "owner": "demo",
              "name": "repo",
              "ref": "refs/heads/feature",
              "commit": "0123456789abcdef0123456789abcdef01234567"
            },
            "workflow": {
              "name": "guarded-run",
              "run_number": 1,
              "trigger": "pull_request"
            },
            "agents": [
              {
                "id": "openai-codex",
                "provider": "openai",
                "capabilities": ["code"]
              }
            ],
            "decisions": [],
            "budgets": {
              "tokens": 2000,
              "currency": { "amount": 0, "units": "USD" }
            },
            "artifacts": [],
            "signatures": [
              {
                "issuer": "sigstore",
                "timestamp": "2024-01-01T00:00:00Z",
                "signature": "-----BEGIN SIGNATURE-----fake-----END SIGNATURE-----",
                "rekor_entry": "https://rekor.dev/entry/2"
              }
            ]
          }
          JSON

      - name: Run Guard Action
        uses: ./action
        with:
          policy: examples/protected-path/policy.yaml
          manifest_glob: out/*.json
          budget_tokens: 5000

      - uses: actions/upload-artifact@v4
        with:
          name: agent-hq-guard-manifest
          path: out
